### ISSUE TITLE
iy+<out of range offset> quietly assembles offset as 0

### ISSUE THREAD

**Issue by Runer112** [alberthdev/spasm-ng#19]
It seems that any index+ofs8 instruction has this behavior. If the offset is out of range, the offset is assembled as 0 and no warning or error is produced.

**Comment by tari** [comment]
A quick look into this seems to indicate there should be an error thrown.

pass\_two.cpp:
```
                case ARG_IX_IY_OFFSET:
                        if (value > 127 || value < -128)
                        {
                                SetLastSPASMError(SPASM_ERR_INDEX_OFFSET_EXCEEDED, value);
                                value = 0;
                        }
                        write_out (value & 0xFF);
                        break;
```

But I can repro:
```
    ld a,(ix+128)
```
assembles successfully. Will require more in-depth investigation.

**Comment by alberthdev** [comment]
Could someone take a look at PR #34 and see if that solves the problem?
