### ISSUE TITLE
save_console_attributes invokes undefined behavior

### ISSUE THREAD

**Issue by tari** [alberthdev/spasm-ng#3]
`save_console_attributes` in `console.cpp` has no body when `WIN32` is not true at compile-time, meaning the non-void function is returning void.

This compiles wrong with a sufficiently smart compiler:
```javascript
function __Z23save_console_attributesv() {
 var $0 = 0, label = 0, sp = 0;
 sp = STACKTOP;
 STACKTOP = STACKTOP + 16|0; if ((STACKTOP|0) >= (STACK_MAX|0)) abort();
 _llvm_trap();
 // unreachable;
 return 0|0;
}
```

I've patched it out just by adding an `#else` branch to the `#ifdef` in the function to always return 0 on non-Windows.

**Comment by alberthdev** [comment]
Thanks for the fix! Merged.
