### ISSUE TITLE
Possible support for MinGW compiling?

### ISSUE THREAD

**Issue by mateoconlechuga** [alberthdev/spasm-ng#45]
This would be absolutely fantastic. I'd be happy to add it myself if I knew where to start :)

EDIT: Actually, it appears that I just have to install some libraries... will report back

**Comment by alberthdev** [comment]
Are you trying to do this on Windows or on Linux (cross-compiling to MinGW/Windows)?

It looks like @jacobly0 submitted a PR (#46) for performing a cross-compilation on Windows - haven't gotten a chance to see if this works natively on Windows MinGW (don't have it installed/running at the moment)!
