### ISSUE TITLE
Trouble cross compiling using mingw

### ISSUE THREAD

**Issue by NonstickAtom785** [alberthdev/spasm-ng#57]
I have been trying to compile the https://github.com/NonstickAtom785/spasm-ng/tree/feature/app-name-var-size branch of spasm-ng. I was able to compile it normally, but I'm still having issues cross compiling. Here's the paste bin of the errors.

https://pastebin.com/3M4KSCAY

**Comment by jacobly0** [comment]
That means either you don't have the cross toolchain installed or it is not in your path.

**Comment by NonstickAtom785** [comment]
Where can I get the cross toolchain?

**Comment by jacobly0** [comment]
Looks like that installs it with a threads suffix, so you'll have to specify `CC=i686-w64-mingw32-g++-win32` manually.

**Comment by NonstickAtom785** [comment]
Ok. Do I need to remove the `CROSS_COMPILE` from my version of the `makefile`? Or will it work without it being removed? I'm asking because the ISWIN needs to be set in-order for some lines to work I think, specifically line 41.
```
EXE = $(if $(ISWIN),spasm.exe,spasm)
```
Sorry again. I've been trying to compile for Windows from linux for a week now with no success.

My taking from your last statement.
`make CC=i686-w64-mingw32-g++-win32`
