### ISSUE TITLE
Compiling to raw binary and not calculator app

### ISSUE THREAD

**Issue by sorenbug** [alberthdev/spasm-ng#58]
Is spasm-ng able to compile to raw ez80 binaries?

**Comment by tari** [comment]
Yes. The output format is [automatically detected based on the filename](https://github.com/alberthdev/spasm-ng/blob/e6e9a42ab95bd25d8cf92607f270e7a34efd8edf/export.cpp#L77). Naming the output `*.bin` or with any unrecognized extension will output a raw binary (emitting a warning in the latter case).

**Comment by sorenbug** [comment]
Cool, thanks.
