### ISSUE TITLE
24 bit jump?

### ISSUE THREAD

**Issue by sorenbug** [alberthdev/spasm-ng#59]
The 3rd instruction after disassembling my CE rom with zdis is `jp.lil $000e4f` which spasm doesn't recognize. What's the replacement? Doing `.ASSUME ADL=1` and then just `jp` throws the same error.

**Comment by jacobly0** [comment]
If you want to assemble ez80 code you have to pass the `-E = Assemble eZ80 code` flag.

**Comment by sorenbug** [comment]
I am passing `-E`:
![image](https://user-images.githubusercontent.com/7751296/74077983-c16b7f80-49d9-11ea-8e70-7c3fafe7fa72.png)

**Comment by sorenbug** [comment]
Here's `cehead.asm`:
```asm
.ASSUME ADL=1
di
rsmix
jp.lil $000e4f
di
rsmix
jp $0015f5
di
rsmix
jp.lil $020110
di
rsmix
jp.lil $020114
di
rsmix
jp.lil $020118
di
rsmix
jp.lil $02011c
di
rsmix
jp.lil $020120
ex af, af'
exx
push ix
push iy
```

**Comment by jacobly0** [comment]
Spasm requires every line containing an instruction to start with whitespace, usually one tab is used.  For a modern, more powerful, ez80 assembler with fewer bugs and that doesn't have this restriction, there's also [fasmg](https://github.com/jacobly0/fasmg-ez80/tree/calm) as an option.

**Comment by sorenbug** [comment]
Sounds good, I think I'll use fasm then.

**Comment by jacobly0** [comment]
If you have more general fasmg and/or ez80 questions I would suggest asking on the EFNet IRC #ez80-dev channel.
