### ISSUE TITLE
Dealing with illegal opcodes

### ISSUE THREAD

**Issue by CattenWithGun** [alberthdev/spasm-ng#89]
I'm not sure if this is a problem with spasm-ng or a problem with the way I'm using it. I found a program with an illegal opcode:
`rlc (iy+$C6),e`
...And spasm-ng is giving me an error : "the opcode RLC was given invalid operands". I'm using [this](https://clrhome.org/table/#%20) opcode table which shows illegal as well as legal opcodes, and so I'm wondering if there is support for compiling illegal opcodes with spasm-ng or if I should find some other way around this issue. According to that opcode table, rlc (iy+d),e should be a valid (although illegal), opcode.

**Comment by jacobly0** [comment]
`d` is a *signed* 8-bit **d**isplacement, so the valid range is `iy-128` to `iy+127`, or `iy-$80` to `iy+$7F`.

**Comment by tari** [comment]
The out of range operand seems unrelated to how this looks like it's meant to be an [autocopy instruction](http://www.z80.info/z80undoc.htm), which I assume is the real error: I don't think undocumented instructions are supported in general.

**Comment by calc84maniac** [comment]
To me it looks like autocopy instructions [are supported](https://github.com/alberthdev/spasm-ng/blob/5f0786d38f064835be674d4b7df42969967bb73c/opcodes.cpp#L604), but the copy destination is specified as the first parameter.

**Comment by tari** [comment]
That's what I get for assuming undocumented instructions aren't supported. 🙃  So the only issue with the original report is that the operand order was wrong, and once you fix that you correctly get an error about the offset being too large.

Seems like everything worked as intended.
